version: "3.8"

services:
  secure-vault:
    build: .
    container_name: secure-vault-system
    working_dir: /app
    volumes:
      - .:/app
    command: npx hardhat test
    ports:
      - "8545:8545"
